import { StyleSheet } from "react-native";

const LoginStyle = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 16,   
  },
  verifycontainer: {
    flex: 1,
    alignItems: 'center',
    marginTop:40,
    justifyContent: 'center',
    padding: 16,   
  },
  background: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  overlay: {
    padding: 20,
  },
  section: {
    padding: 16,
  },
  getButton: {
    backgroundColor: '#D39505',
    paddingVertical: 14,
    paddingHorizontal: 80,
    borderRadius: 10,
    width: '80%',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 5,
    alignSelf: 'center',
    marginTop: 500,
  },
  getText: {
    color: 'white',
    textAlign: 'center',
    fontSize: 20,
    fontFamily: "Messina",
    fontWeight: 'bold',
  },
  title: {
    fontSize: 30,
    marginBottom: 24,
    fontFamily: "Poppins",
    textAlign: 'center',
    fontWeight: 'bold',
  },
  Regtitle: {
    fontSize: 30,
    marginTop:50,
    marginBottom: 24,
    fontFamily: "Messina",
    textAlign: 'center',
    fontWeight: 'bold',
  },
  buttonContainer: {
    flexDirection: 'row',
    marginBottom: 24,
  },
  loginButton: {
    backgroundColor: '#3C6791',
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderTopLeftRadius: 8,
    borderBottomLeftRadius: 8,
    fontFamily: "Messina-Regular",
    height: 45,
    width: '50%',
  },
  registerButton: {
    backgroundColor: '#3C6791',
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderTopRightRadius: 8,
    borderBottomRightRadius: 8,
    width: '50%',
  },
  ClickloginButton: {
    backgroundColor: '#08285E',
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderTopLeftRadius: 8,
    borderBottomLeftRadius: 8,
    height: 45,
    width: '50%',
  },
  ClickregisterButton: {
    backgroundColor: '#08285E',
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderTopRightRadius: 8,
    borderBottomRightRadius: 8,
    width: '50%',
  },
  buttonText: {
    color: 'white',
    fontWeight: 'bold',
    textAlign: 'center',
    fontFamily: "Messina-Regular",
  },
  numBox: {
    width: 50,
    height: 50,
    borderWidth: 1,
    borderColor: '#d1d5db',
    borderRadius: 8,
    textAlign: 'center',
    fontSize: 24,
    marginHorizontal: 4,
    fontWeight: 'bold',
  },
  numText: {
    width: '25%',
    height: 50,
  },
  verifyText: {
    textAlign: 'center',
    fontSize: 16,
    fontWeight: 'bold',
  },
  otpContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginVertical: 10,
    marginBottom: 10,
  },
  otpInput: {
    width: 55,
    height: 60,
    borderWidth: 1.5,
    borderColor: '#08285E',
    backgroundColor: '#F1F5F9',
    borderRadius: 10,
    textAlign: 'center',
    fontSize: 22,
    fontWeight: 'bold',
    color: '#08285E',
    marginHorizontal: 6,
    elevation: 3,
  },
  inputContainer: {
    width: '100%',
    marginBottom: 16,
    
  },
  label: {
    fontSize: 14,
    color: 'black',
    marginBottom: 4,
    fontWeight: 'bold',
  },
  input: {
    borderWidth: 1,
    borderColor: '#CBD5E0',
    borderRadius: 8,
    padding: 10,
    fontSize: 16,
    color: '#4A5568',
    fontWeight: 'bold',
  },
  sendCodeButton: {
    backgroundColor: '#D39505',
    paddingVertical: 12,
    paddingHorizontal: 32,
    borderRadius: 8,
    height: 50,
    width: '100%',
    alignContent: 'center',
  },
  sendCodeButtonText: {
    color: 'white',
    textAlign: 'center',
    fontSize: 16,
    marginTop: 1,
    fontFamily: "Poppins",
    fontWeight: 'bold',
  },
  dashContainer: {
    paadding: 1,
    marginBottom: '100%',
  },
  dashBackground: {
    flex: 1,
  },
  proLine: {
    color: 'black',
    fontWeight: 'bold',
    textAlign: 'center',
    fontSize: 40,
  },
  profButton: {
    backgroundColor: 'black',
    paddingVertical: 12,
    paddingHorizontal: 32,
    borderRadius: 30,
    height: 60,
    width: 50,
    marginTop: '50%',
  },
  dashText: {
    color: '#D39505',
    fontSize: 25,
    fontWeight: 'bold',
  },
  sidePage: {
    backgroundColor: 'white',
    height: '100%',
    width: '50%',
  },
  verifyTitle: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#08285E',
    marginBottom: 10,
    textAlign: 'center',
    fontFamily: 'Poppins',
  },
  emailText: {
    fontSize: 16,
    color: '#3C6791',
    fontWeight: 'bold',
    marginBottom: 20,
    textAlign: 'center',
  },
  resendText: {
    marginTop: 20,
    color: '#3C6791',
    textAlign: 'center',
    fontSize: 14,
    textDecorationLine: 'underline',
    fontFamily: 'Poppins',
    fontWeight: 'bold',
  },
  
});

export default LoginStyle;
